name: Dog House Studios
favicon: null
layout_spectrum: 0.2273938856087625
typography_spectrum: 0.9589340821839869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4503756717313081
  lightness: 0.31158160394988954
  saturation: 0.7168298293836415
  rhythmicContrast: 0.4836021636147052
purpose: []
